import { ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import bcrypt from 'bcrypt';
import type { UserRole } from '../auth/auth.types.js'; import { PrismaService } from '../prisma/prisma.service.js'; import type { CreateStoreDto } from './dto/create-store.dto.js'; import type { CreateUserDto } from './dto/create-user.dto.js'; import type { ListQueryDto } from './dto/list-query.dto.js';
type User = { id: string; name: string; email: string; passwordHash: string; address: string; role: UserRole }; type Store = { id: string; name: string; email: string; address: string; ownerId: string }; type Rating = { id: string; userId: string; storeId: string; rating: number };
type Varchar<N extends number> = string & { readonly __varcharLength: N }; const varchar = <N extends number>(value: string) => value as Varchar<N>;
@Injectable()
export class AdminService {
  constructor(private readonly prisma: PrismaService) {}
  async dashboard() { const [users, stores, ratings] = await Promise.all([this.collect(this.prisma.client.orm.public.User.all()), this.collect(this.prisma.client.orm.public.Store.all()), this.collect(this.prisma.client.orm.public.Rating.all())]); return { totalUsers: users.length, totalStores: stores.length, totalRatings: ratings.length }; }
  async createUser(dto: CreateUserDto) { if (await this.prisma.client.orm.public.User.where({ email: varchar<255>(dto.email) }).first()) throw new ConflictException('An account with this email already exists.'); const passwordHash = await bcrypt.hash(dto.password, 12); const user = await this.prisma.client.orm.public.User.create({ name: varchar<60>(dto.name), email: varchar<255>(dto.email), passwordHash: varchar<255>(passwordHash), address: varchar<400>(dto.address), role: dto.role }); return this.publicUser(user); }
  async listUsers(query: ListQueryDto) { const users = await this.collect(this.prisma.client.orm.public.User.all()); const filtered = users.filter((user) => this.matches(user, query) && (!query.role || user.role === query.role)); return this.paginate(filtered.map((user) => this.publicUser(user)), query); }
  async userDetail(id: string) { const [user, stores, ratings] = await Promise.all([this.prisma.client.orm.public.User.where({ id }).first() as Promise<User | null>, this.collect(this.prisma.client.orm.public.Store.all()), this.collect(this.prisma.client.orm.public.Rating.all())]); if (!user) throw new NotFoundException('User not found.'); const result: Record<string, unknown> = this.publicUser(user); if (user.role === 'STORE_OWNER') { const owned = stores.filter((store) => store.ownerId === user.id); const ownedRatings = ratings.filter((rating) => owned.some((store) => store.id === rating.storeId)); result.averageRating = ownedRatings.length ? Number((ownedRatings.reduce((sum, r) => sum + r.rating, 0) / ownedRatings.length).toFixed(2)) : null; } return result; }
  async createStore(dto: CreateStoreDto) { const owner = await this.prisma.client.orm.public.User.where({ id: dto.ownerId }).first() as User | null; if (!owner || owner.role !== 'STORE_OWNER') throw new NotFoundException('Store owner not found.'); return this.prisma.client.orm.public.Store.create({ name: varchar<60>(dto.name), email: varchar<255>(dto.email), address: varchar<400>(dto.address), ownerId: dto.ownerId }) as Promise<Store>; }
  async listStores(query: ListQueryDto) { const [stores, ratings] = await Promise.all([this.collect(this.prisma.client.orm.public.Store.all()), this.collect(this.prisma.client.orm.public.Rating.all())]); const data = stores.filter((store) => this.matches(store, query)).map((store) => ({ id: store.id, name: store.name, email: store.email, address: store.address, overallRating: this.average(ratings.filter((rating) => rating.storeId === store.id)) })); return this.paginate(data, query); }
  async listRatings() { const [ratings, users, stores] = await Promise.all([this.collect(this.prisma.client.orm.public.Rating.all()), this.collect(this.prisma.client.orm.public.User.all()), this.collect(this.prisma.client.orm.public.Store.all())]); return ratings.map((rating) => ({ ...rating, user: users.find((user) => user.id === rating.userId) && this.publicUser(users.find((user) => user.id === rating.userId)!), store: stores.find((store) => store.id === rating.storeId) })); }
  private matches(item: { name: string; email: string; address: string }, query: ListQueryDto) { if (!query.search) return true; return item.name.toLowerCase().includes(query.search) || item.email.toLowerCase().includes(query.search) || item.address.toLowerCase().includes(query.search); }
  private paginate<T extends Record<string, unknown>>(rows: T[], query: ListQueryDto) { const field = query.sortBy as keyof T; const direction = query.sortOrder === 'asc' ? 1 : -1; rows.sort((a, b) => String(a[field]).localeCompare(String(b[field])) * direction); const total = rows.length; const start = (query.page - 1) * query.limit; return { data: rows.slice(start, start + query.limit), meta: { total, page: query.page, limit: query.limit, totalPages: Math.ceil(total / query.limit) } }; }
  private publicUser(user: User) { const { passwordHash: _, ...safe } = user; return safe; } private average(ratings: Rating[]) { return ratings.length ? Number((ratings.reduce((sum, rating) => sum + rating.rating, 0) / ratings.length).toFixed(2)) : null; } private async collect<T>(rows: AsyncIterable<T>): Promise<T[]> { const results: T[] = []; for await (const row of rows) results.push(row); return results; }
}
